- src/main/java/zd/zero/waifu/motivator/plugin/alert/AlertAssetProvider.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/java/zd/zero/waifu/motivator/plugin/providers/UniqueValueProvider.java
Persist the consumed assets to not play until all of it are consumed. This implementation improved the way how WMP alerts and shows Waifu of the Day to avoid repeating the content.
Resolves #28
> feat: WMP-028 persist the consumed assets 

- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlert.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlertImpl.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/notification/WaifuMotivatorNotifier.java
The `Notification#isExpired` is always called even if the user clicked the close notification, so I needed to compute the average duration of the Notification to tell whether it already expired or not and the Notification usually closes at `10s`, the duration sometimes goes up to `10s` to `13s` and the minimum value is the `10s` as a safe bet we used it to the condition, the reason why it doesn't have a prefix duration because disposing the Notification is requested to the Event Dispatch Thread (EDT) and not executed immediately.
Resolves #42
> bug: WMP-042 resolve sound stopping when the alert is expired

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProjectComponent.java
This PR prevents triggering sayonara on each project close events, and would only trigger on the last project closed.
Resolves #53
> feat: global project closing sayonara

- .idea/compiler.xml
- .idea/misc.xml
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProjectComponent.java
Bumped the IJ support version to `2020.1` and resolved some deprecated APIs. For migration of plugin components to use modern APIs (#66).
> chore: bump idea support version to 2020.1

- src/main/java/zd/zero/waifu/motivator/plugin/actions/PluginSettingsAction.java
- src/main/resources/META-INF/plugin.xml
This PR added a new menu to the plugin toolbar menu to easily navigate to the plugin settings.
This will open up the "Waifu Motivator" settings page.
Resolves #69
> feat: add settings navigation menu to plugin toolbar menu

- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/resources/waifu_of_the_day/darcula_style.css
This PR added a different styling if the theme is dark to improve the readability on Waifu of the Day.
Resolves #73
> bug: properly style waifu of the day based on theme

- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorPluginState.java
This PR updated the state which instead of the object `WaifuMotivatorState` is used, the  `WaifuMotivatorPluginState` was used.
Resolves #83
> bug: assertion error in plugin state

- src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java
Decided to remove the dependency on `org.apache.commons.io.FilenameUtils` which is included in IJ classpath and the plugin package doesn't include it explicitly and not present in Webstorm platform that results to `NoClassDefFound` exception
Resolves #84
> bug: webstorm no class def found

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlertImpl.java
The reason why `IllegalStateException` is thrown is it tries to stop the player even though it is not started because it was disabled at the first place, the solution was to check if the sound is enabled.
Resolves #95
> fix: IllegalStateException when sound is disabled

- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
- src/main/resources/messages/MessageBundle.properties
Updated the message bundle to include settings tooltips to add more information to what the setting does.
Resolves #94
> chore: settings tooltip descriptions

- .editorconfig
- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
- src/main/resources/META-INF/plugin.xml
Resolves #110 
This PR added a condition to add listeners only if the project is not opened beforehand to avoid multiple listeners attached to the project.
> fix: waifu unit tester executes multiple times

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
Resolves #112 
This PR only allows one startup event to be invoked when there are multiple projects opened to avoid having multiple different sounds played for each project.
> fix: multiple different startup sounds

- src/main/java/zd/zero/waifu/motivator/plugin/assets/LocalAssetService.kt
I wrote code attempting to read the asset-checks json before initializing the tool that reads json.
:facepalm:
> fix:  enable re-hydration of local asset checks on startup

- src/main/java/zd/zero/waifu/motivator/plugin/alert/VisualWaifuNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
Resolves #140 
Updated the balloon alert style.
A bit of a hack but we can now avoid displaying a scrollbar, changed the layout data to enable `welcomeScreen` flag.
This will then make the ballon to use text content instead of adding a pane.
https://github.com/JetBrains/intellij-community/blob/b59fbaba724d5c7e016431383a4b28963cba4ae8/platform/platform-impl/src/com/intellij/notification/impl/NotificationsManagerImpl.java#L570-L572
The consequence is not showing the balloon icon on the left side, but I think that this is a lesser consequence for avoiding scrollbars.
https://github.com/JetBrains/intellij-community/blob/b59fbaba724d5c7e016431383a4b28963cba4ae8/platform/platform-impl/src/com/intellij/notification/impl/NotificationsManagerImpl.java#L574-L588
Now that we don't have the icon on …
> fix: visual motivation alert style

- docs/CHANGELOG.md
I hate myself for this, we have a redundant plugin title because `CHANGELOG.md` file contains the title.
> fix: redundant title description

- build.gradle
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java
Fixes #153 
This wasn't just a WebStorm/Jest issue, if a any JUnit test was annotated with `@Ignore` would also cause this bug.
> fix: Ignored tests with no failures is success

- .github/workflows/pre-merge.yml
I am writing a bunch of tests for #159 and I require a JRE 11+ to make the happy.
Building the plugin with a JDK 11 and have it run on JDK 8 should be okay. If it doesn't, I'm not sure how my Doki-Theme plugin works then :)
> chore: bump pre-merge pipeline JRE to 11

- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/java/zd/zero/waifu/motivator/plugin/assets/LocalStorageService.kt
- src/main/java/zd/zero/waifu/motivator/plugin/player/DefaultWaifuSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java
Closes #167 
So when we log things as `error` that gives the user the option to report the error. 
I would prefer that any error that the user reports come from something unexpected and actionable (ie un-caught runtime exceptions). Reporting a checked exception (one that we know will happen) that we just log is not very useful, in my opinion. We knew it was going to happen and we just wanted to log it. If we keep it at `warn` it will still show in the log. That way the user can manually report the issue if it is severe enough. Plus this issue has only been reported once, so it is not a wide spread issue.
I only left ~~one~~ two error logs, because that error prevents the plugin from ever initializing.
> chore: address checked exception error reporting

- src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java
Closes #172 
I tested this on both IntelliJ and WebStorm. It works with it. If I removed the `implementation 'commons-io:commons-io:2.6'` line from the build gradle, it would stop working in WebStorm, so it is safe to say this works as expected.
> chore: back to using filename utils

- src/main/java/zd/zero/waifu/motivator/plugin/listeners/TaskListener.kt
Closes #184 
The fix was pretty easy, just ask for the project reference in the constructor and the platform supplies it.
> fix: only show task events on correct project

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
Closes #186 
This happened when I restarted my IDE and had many projects open before. Well I wanted to close one of the projects, before it got done indexing. So the plugin had not initialized yet.
> fix: able to close project before project is initalized

- src/main/java/zd/zero/waifu/motivator/plugin/listeners/ExitCodeListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
- src/main/resources/messages/MessageBundle.properties
Closes #192 
Rather than hard code values that should be allowed, I chose to start off with some defaults that can be modified by the users as they come across more exit codes.
> fix: allow customization of allowed exit codes.

- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
- src/main/resources/messages/MessageBundle.properties
Resolves #190 
This PR group the event settings.
Main section is now trimmed down to just actions and other features
The events section now contains all of the sections and only the Idle and Exit Code Events have borders for they have other components.
This PR also updated the text content of the settings to make it more consistent with other events.
> feat: group event settings

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/PluginInstallListener.kt
- src/main/resources/META-INF/plugin.xml
Closes #198 
Lol, so this was a pain to simulate testing, however I think I narrowed it down to this quick fix.
I think that this can be done without having to reload each project though. It would require to have one Application Level listener that listens to project life-cycles instead of many project life-cycle listeners. However, I think this is good enough for the time being. Maybe that could be a target for 1.4 ?
Fun Fact: Project Listeners are not instantiated on plugin load.They only get instatiated when a relevant event is triggered. So it comes into existence when the project closes, but not when the plugin is first loaded :cry:
> bug: enable plugin to work without IDE restart

- src/main/java/zd/zero/waifu/motivator/plugin/listeners/ExitCodeListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
Closes #204 
To enable debug logging to observe the exit code in the logs, all you have to do is use the `Help | Diagnostic Tools | Debug Log Settings..`
and add the line `#zd.zero.waifu.motivator.plugin.listeners.ExitCodeListener` to it.
Should that be added to the docs?
> chore: fix memory leak and added exit code debug log

- .github/workflows/pre-merge.yml
Bumping GitHub Action to latest released version, [release notes for v1.0.3 here](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/releases/tag/v1.0.3).
> Bumping GitHub Action to latest version

- src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
- src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/tools/AssetTools.kt
- src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
- src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
This PR resolves the freezing of UI, as this will prioritize local assets, and every time an event is triggered it'll run a background task to fetch a new asset. For the first asset category, it'll fallback to original behavior to download and use the asset, but it's running on a separate thread so this won't block the EDT.
You can now spam the *Waifus* without delay!
> fix: ui freezing on visual notifications

- .gitignore
- build.gradle
- buildSrc/src/main/kotlin/BuildTools.kt
- buildSrc/src/main/kotlin/CreateReleaseNotes.kt
- buildSrc/src/main/kotlin/HtmlToMdExtension.kt
- buildSrc/src/main/kotlin/waifu-motivator-build-plugin.gradle.kts
This PR reverts the changelog's content with `.html` extension back to `.md` as the plugin `'org.kordamp.gradle.markdown'` converts it to the target extension during the md to HTML process.
> chore(gradle): revert changelog extension from html to md

- build.gradle
- src/main/java/zd/zero/waifu/motivator/plugin/assets/LocalAssetService.kt
Closes #229 
The `LocalAssetService` is a singleton and now that asset downloading can happen in many threads, there are edge cases where on thread is writing to the asset check map while the other is trying to serialize it into json. So I chose to change the map to a `ConcurrentMap` so that the asset check can be written to and updated at the same time.
See this [issue for more details](https://github.com/google/gson/issues/1159#issuecomment-330535301)
> fix: multi-thread safe asset check serialization

- src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
- src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
- src/test/resources/visuals/assets.json
- src/test/resources/visuals/updated-assets.json
Closes #242 
Turns out that this was probably just an issue for me because I was probably messing around with the `assets.json` file, and broke something :sweat_smile: .
Anyways, having this in place should prevent the plugin from breaking.
> fix: handling malformed definitions better

- gradle.properties
Bump target `untilBuildVersion` to `211.*` to support Intellij `v2021.1`.
> chore: bump untilBuildVersion to 211.*

- README.md
For the `doki-theme.gif` file, I pulled it from [here.](https://github.com/doki-theme/doki-theme-jetbrains/blob/master/assets/screenshots/flagship_themes.gif) In case that it is updated, we wouldn't have any broken images in this repo. Hope that it's fine to have a copy of your gif here 🤞.
> docs: doki-theme integration

- .github/workflows/dev-release.yml
I figured I'd get a jump start on this, I think it should still work without these changes because GitHub should redirect to the actual location.
So I'll leave this in draft for now. Do you think we should also include the documentation updates?
Relevant issue #270
> chore: organization migration

- README.md
- buildSrc/src/main/kotlin/CreateReleaseNotes.kt
- docs/CHANGELOG.md
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
- src/main/resources/META-INF/plugin.xml
This PR updates the base links to point to the new organization URL `https://github.com/waifu-motivator/`.
Resolves #270
> docs: update links to organization

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UserOnboarding.kt
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
This PR addresses the Sayonara on a fresh install of the plugin.
Initially, I wanted to use `UserOnboarding#isNewVersion` but the version is already updated on the project opened, so we can't use it on project closed where Sayonara is triggered. So I opt-in adding a new plugin state.
> feat: enhance plugin installation experience

- build.gradle
- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetService.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
- src/test/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProviderTest.kt
Closes #278 
I thought that it was weird that as I was adding more grouped assets that it was choosing to play audio assets outside if it's group.
I would like this to be part of the next release, before I start to group a bunch of audio with a bunch of assets in the fancy new `Waifu Asset Management` UI!
> Sneak peek
> Constrain grouped assets to group.

- src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationFactory.kt
Closes #280
So I just fixed the symptom of the issue and did not address the underlying issue.
I think we may need to re-visit how the listeners are disposed on project close. 
That way we don't have motivation events with disposed projects in the first place :100:
> fix: not attempting to show motivation for disposed projects

- build.gradle
- docs/CHANGELOG.md
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/AniMemePluginPromotionRunner.kt
- Grabbing the parent window for the ani-meme dialog on the EDT thread because it really didn't like it happening on one of the pooled applicaiton threads.
Closes #304 
Apparently this has been happening for a while now. 
I didn't notice because the Sentry errors weren't very helpful in notifying me that there was an issue in the EAP builds (I'll have to look into that)
Any users that have encountered this issue will be given the v2.0 migration dialog window. Which I don't think is that big of a deal, it accomplishes the same thing. It just assumes the user had used the old notification system before.
I tested this on both `2020.3.3` and `2021.1` and the on-boarding works!
> fix: new user on-boarding errors

- .github/workflows/build.yml
- .github/workflows/dev-release.yml
- build.gradle
This PR resolves #326.
Removed the insecure env setup and use [`wmp-env-action@1.3.1`](https://github.com/waifu-motivator/wmp-env-action/releases/tag/v1.3.1)
> fix: canary deployment

- build.gradle
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/MemePromotionDialog.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/META-INF/zd.zero.waifu-motivator-plugin-io.unthrottled.amii.xml
This PR resolves #314 
Adds support for IJ 2021.2 and drops the explicit [optional dependency](https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html) to `io.unthrottled.amii` as we're not using any extension points, but this doesn't mean that the integration of Anime Memes (AMII) is removed, for it fails on `runPluginVerifier` tasks.
Tested installing this without the `zd.zero.waifu-motivator-plugin-io.unthrottled.amii.xml` file, and it still works fine.
> chore: 2021.2 build support

- .github/workflows/release.yml
Fix issues with Gradle `buildPlugin` task
```
Entry waifu-motivator-plugin/lib/v2.1.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```
> fix: buildPlugin duplicate handling

- .github/workflows/release.yml
Fix issues with the `buildPlugin` that is part of the `publishPlugin` which finds duplicates of the built jar.
```
> Task :buildPlugin FAILED
FAILURE: Build failed with an exception.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
* What went wrong:
Execution failed for task ':buildPlugin'.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> Entry waifu-motivator-plugin/lib/v2.1.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:com …
```
> fix: publishPlugin release workflow

- CHANGELOG.md
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/MemePromotionDialog.kt
Even though the previous build properly installs in the IJ version `2021.2`. The IJ marketplace doesn't accept it and shows a conflict. Reverts to the platform target version `2020.2.4`.
~~Will merge and release this once `v2.1.2.beta.1fco11b95` is available in canary.~~
> fix: incompatible dependencies to 2021.2

- CHANGELOG.md
- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
- Updated Waifu of the Day JSON decoding to be decoded in UTF-8.
Closes #484 
| Before | After |
| --- | --- | 
| ![Screenshot 2023-01-23 195029](https://user-images.githubusercontent.com/15972415/214197557-f1203bd4-d37e-4823-9020-f3d6e497517a.png) | ![Screenshot 2023-01-23 194906](https://user-images.githubusercontent.com/15972415/214197568-026384d2-4c9b-41ad-9b56-f69d9569c4b2.png) |
> bug: Rendering 漢字 better
