waifu-motivator/waifu-motivator-plugin

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivator.java
This PR won't log the notification event.
This will resolve Issue #2
> feat: WMP-002 notifications that are not logged

- .gitignore
- .idea/misc.xml
- .idea/sonarlint/issuestore/index.pb
- .idea/waifu-motivator-plugin.iml
- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivator.java
- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProjectComponent.java
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorPluginSettings.java
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.java
- src/main/resources/META-INF/plugin.xml
This PR adds the ability to disable sound and notification at startup.
This will resolve Issue #3.
> feat: WMP-003 ability to disable sound and notification at startup

- README.md
> Update README file for details in running it locally

- .idea/misc.xml
- src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
- src/main/resources/META-INF/plugin.xml
This PR implemented the actions for requesting motivation from your waifu, there are multiple ways to request a motivation.
The menu is located before the 'Help' menu.
For now, the hotkey for the motivation action is `alt M`.
Resolves #9
> feat: WMP-009 waifu motivation on demand

- .github/workflows/gradle.yml
This PR added a GitHub workflow for building and checking project tests.
> chore(workflow): add github workflow

- .gitignore
- .idea/compiler.xml
- .idea/jarRepositories.xml
- README.md
- build.gradle
- gradle.properties
- parts/pluginChanges.html
- parts/pluginDescription.html
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java
- src/test/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImplTest.java
This PR updated the documentation and bumped IJ to version `2019.3` which introduced breaking changes for Notifications and already resolved.
> docs: update readme file and bump IJ target to 2019.3

- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlert.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlertImpl.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/notification/WaifuMotivatorNotifier.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/sound/DefaultWaifuMotivatorSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/sound/SoundClipUtil.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/sound/WaifuMotivatorSoundPlayer.java
This PR implemented the ability to stop the audio playing at the background when the alert notification is closed.
Resolves #29
> feat: WMP-029 stop playing the audio if the alert was closed

- src/main/java/zd/zero/waifu/motivator/plugin/alert/AlertAssetProvider.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/java/zd/zero/waifu/motivator/plugin/providers/UniqueValueProvider.java
- src/test/java/zd/zero/waifu/motivator/plugin/providers/UniqueValueProviderMock.java
- src/test/java/zd/zero/waifu/motivator/plugin/providers/UniqueValueProviderTest.java
> bug: WMP-039 asset provider not properly categorizing on the next invocation

- README.md
- src/main/resources/waifu_of_the_day/WaifuOfTheDayTemplate.html
This PR updates the copy text 'source' to use 'sauce' instead as it is more fitting on the Anime community.
Resolves #50
> chore: update text source to sauce

- src/main/java/zd/zero/waifu/motivator/plugin/MessageBundle.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
- src/main/resources/messages/MessageBundle.properties
This PR implemented the Message Bundle for the plugin to easily maintain the text and adds an opportunity for the plugin's texts to be i18n.
Resolves #26
> feat: create a message bundle

- .idea/compiler.xml
- build.gradle
- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProjectComponent.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/AlertAssetProvider.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlertAsset.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlertFactory.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuMotivatorAlertImpl.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/sound/WaifuMotivatorSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/DefaultWaifuSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/EmptyWaifuSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/SoundClipUtil.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayer.java
- src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java
This PR added support for playing `mp3` files, we should extend this by having a different sound player implementation and when it is not currently listed, we should check if we can play it.
Resolves #56
> feat: add support for playing mp3 file format

- .idea/codeStyles/Project.xml
- build.gradle
- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorPluginState.java
- src/main/resources/META-INF/plugin.xml
- src/main/resources/messages/MessageBundle.properties
This PR removed the implementation of using the [Plugin Components](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_components.html) to support Dynamic Plugins of IJ 2020.1
Resolves #66
> feat: migrate to dynamic plugin

- gradle.properties
- parts/pluginChanges.html
> chore: bump version to WMP v1.1.1

- gradle.properties
- parts/pluginChanges.html
> chore: bump version to WMP v1.1.2

- parts/pluginChanges.html
> docs: reduce indent level for plugin changes

- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
This PR improves the structure and added some checks to prevent `null` exceptions.
> refactor: improve waifu of the day dialog code structure

- .github/workflows/gradle.yml
- .github/workflows/pre-merge.yml
> chore: Add plugin verification to pre-merge action.

- .editorconfig
This PR added new rules to `.editorconfig` file.
> chore: update editor config

- src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java
- src/main/java/zd/zero/waifu/motivator/plugin/tools/Debouncer.kt
- src/test/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImplTest.java
Fixes #124 
I couldn't figure out how to wire into the actual test pass/fail in a reasonable amount of time. So I just opted to just use a hacker solution. Got a bunch of request and you don't know why? Just debounce it, it will be fine :joy:
> fix: run at most one test notification

- build.gradle
- gradle.properties
Fixes #127 
Everything still appears to be functional.
> chore: 2020.2 build support

- build.gradle
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UserOnboarding.kt
- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
- src/main/resources/META-INF/plugin.xml
Fixes #130 
Reports the plugin's thrown exceptions with a lot of helpful and anonymous data to help debug issues with the plugin.
I would have added you to my sentry.io team, but that is a paid feature, and I am not paying for it yet. Sorry! If/When I do I'll it then :)
You can also set up one of your own, and I can change the config to point to that.
> chore: Added error reporter

- src/main/java/zd/zero/waifu/motivator/plugin/alert/BaseWaifuNotification.kt
Fixes annoying log that shows up every now and then https://pastebin.com/ax9EQHiw
> fix: create notification group once

- src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
- src/main/resources/messages/MessageBundle.properties
Resolves #108 
Updated the title and description settings.
> chore: improve settings descriptions

- src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
- src/main/java/zd/zero/waifu/motivator/plugin/alert/BaseWaifuNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/alert/NonTitledVisualNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/alert/VisualWaifuNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
- src/main/java/zd/zero/waifu/motivator/plugin/motivation/VisualMotivationFactory.kt
Closes #157 
Spam that `Alt+M` combo, yo.
We probably want to re-imagine the random asset picking later, something that gives a more even distribution, without having to worry about showing all the assets. Right now I'm just happy anime girls show up on my IDE at all.
> feat: enable more visual event categories for Motivate Me action

- src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
- src/main/java/zd/zero/waifu/motivator/plugin/actions/PluginSettingsAction.java
- src/main/java/zd/zero/waifu/motivator/plugin/actions/ShowWaifuOfTheDayAction.java
> fix: enable plugin actions during indexing

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
- src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UserOnboarding.kt
- src/main/java/zd/zero/waifu/motivator/plugin/platform/LifeCycleManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateListener.kt
- src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
- src/test/resources/visuals/updated-assets.json
Closes #168 
#173 Makes not having assets of a specific category non-critical. So I wanted to build on top of that. This will not be WIP whenever that PR goes in.
> chore: update asset metadata on version upgrade

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
> chore: 2020.3 build support

- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
- src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
I just wanted these things put in.
> WMP-206 Support: Added remote asset testing

- docs/CHANGELOG.md
> updating the change log to be consistent

- src/main/java/zd/zero/waifu/motivator/plugin/WaifuOfTheDayStartupActivity.kt
This PR now properly uses a disposable parent with and delegated the scheduling to EDT executor service. The disposable used is temporary as the lifetime of Waifu-of-the-Day is short and happens once a day.
> For resources with a shorter lifetime, create a disposable using Disposer.newDisposable() and dispose it manually using Disposable.dispose().
[See reference](https://jetbrains.org/intellij/sdk/docs/basics/disposers.html#choosing-a-disposable-parent)
> fix: use temporary disposable parent

- src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/MoodStatusBarWidget.kt
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/ExitCodeListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/IdleEventListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationFactory.kt
- src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEventListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/personality/Wendi.kt
- src/main/java/zd/zero/waifu/motivator/plugin/personality/core/PersonalityCore.kt
- src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionCore.kt
- src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionEvents.kt
- src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/PositiveEmotionDerivationUnit.kt
- src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/service/WaifuGatekeeper.kt
- src/main/java/zd/zero/waifu/motivator/plugin/settings/PluginSettingsListener.kt
- src/main/java/zd/zero/waifu/motivator/plugin/tools/Debouncer.kt
Closes #252 
[What's new with Kotlin?](https://kotlinlang.org/docs/reference/whatsnew14.html)
TL;DR:
- SAM Conversions for Kotlin Interfaces
- Trailing commas :confetti_ball:
> chore: Upgrading to Kotlin 1.4 features

- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
So I still included it with a separate row to see it differently, even if it's already in the config, and avoid truncating it.
> chore: enhance exception reporting metadata

- docs/CHANGELOG.md
Minor update for the changelog file.
> docs: update changelog bug fix section

- build.gradle
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
This PR fixes some compatibility issues in Gradle and updated platform versions.
> chore: update build

- CHANGELOG.md
- src/main/java/zd/zero/waifu/motivator/plugin/listeners/PluginInstallListener.kt
Not calling a method that throws the `NoSuchElementException` when trying to find projects to initialize the dynamically installed project.
Closes #335
> fix: plugin installation from welcome screen.

- .github/workflows/release.yml
Add changelog job for release workflow
> feat: add changelog update for release workflow

- .github/dependabot.yml
- .github/workflows/release.yml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Update actions, build, and versions based from the [intellij-platform-plugin-template](https://github.com/JetBrains/intellij-platform-plugin-template) stable branch.
Removed unnecessary dependency: `com.googlecode.soundlibs`
> chore: update actions, build, and versions

- build.gradle
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/MemePromotionDialog.kt
- src/main/resources/META-INF/plugin.xml
> feat: 2022.1 build support

- build.gradle
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
- src/main/java/zd/zero/waifu/motivator/plugin/tools/ToolBox.kt
> chore: defer Sentry initialization.

- .github/workflows/dev-release.yml
> chore(deps): bump wmp-env-action from 1.3.1 to 1.3.2

- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/DialogTipPanel.java
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
- src/main/resources/messages/MessageBundle.properties
This PR is for issue: https://github.com/waifu-motivator/waifu-motivator-plugin/issues/262
> Move strings to message bundle

- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/DialogTipPanel.java
- src/main/java/zd/zero/waifu/motivator/plugin/assets/LocalStorageService.kt
- src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/AniMemePluginPromotionRunner.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/MemePromotionDialog.kt
- src/main/resources/META-INF/plugin.xml
This pr is for issue: https://github.com/waifu-motivator/waifu-motivator-plugin/issues/217
* `LocalStorageService`:
Fix parameter is overshadowed warning
* `ErrorReporter`: 
Replace deprecated `toLowerCase` with `lowercase` 
Replace deprecated `DateFormatUtil.formatAboutDialogDate(date)` with `NlsMessages.formatDateLong(date)`
* `AniMemePluginPromotionRunner`:
Pass project param to `AniMemePromotionDialog`
* `MemePromotionDialog`:
Replace deprecated `installAndEnable(Set, Runnable)` with `installEnable(Project, Set, Boolean, Runnable)`
Replace `DialogWrapper.DoNotAskOption` with `com.intellij.openapi.ui.DoNotAskOption`
* `DialogTipPanel`:
Replace `DialogWrapper.DoNotAskOption` with `com.intellij.openapi.ui.DoNotAskOption`
* Upgrade minimum supported version to 221
> Remove deprecated apis

- CHANGELOG.md
- gradle.properties
- src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
- src/main/java/zd/zero/waifu/motivator/plugin/promotion/LedgerMaster.kt
- [WMP-499](https://github.com/waifu-motivator/waifu-motivator-plugin/issues/499) 2023.1 build support
Closes #499
> chore: Added 2023.1 Build Support
